name: UAT

on:
  push:
    branches:
      - Master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy application
        uses: actions/deploy-pages@v2
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
