name: UAT

on:
  push:
    branches:
      - Master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy application
        uses: actions/github-script@v6
        with:
          script: |
            github.actions.createDeployment("UAT", {
              ref: github.ref,
              task: "deploy",
              auto_merge: true,
              environment: "production",
              secrets: {
                MY_DEPLOYMENT_TOKEN: "${{ secrets.Tech_dev }}",
              }
            })
