name: UAT

on:
  push:
    branches:
      - Master  # Change 'Master' to 'master' if your branch name is lowercase

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy application
        run: |
          echo "Creating a deployment"
          echo "ref: ${{ github.ref }}"
          echo "environment: production"

          # Use the 'GITHUB_TOKEN' secret to create a deployment
          gh deployment create \
            --ref "${{ github.ref }}" \
            --environment "production" \
            --auto-merge \
            --token "${{ secrets.GITHUB_TOKEN }}"
